config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # signin/signup customizing
  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signup' => 'devise/registrations#new'
  end

  resources :projects
  root 'projects#index'

  # request
  get '/projects/:id/apply' => 'projects#apply'
  delete '/projects/:id/apply' => 'projects#cancel_apply'

  # mypage
  get '/mypage' => 'user#mypage'
  get '/mypage/edit' => 'user#edit'
  post '/mypage/edit' => 'user#update'

  # my projects
  get '/myprojects' => 'user#myprojects'

  # user information
  get '/user/:id' => 'projects#user'

  # accept
  get '/projects/:id/accept/:requester_id' => 'projects#accept'
  delete '/projects/:id/accept/:requester_id' => 'projects#decline'

  # kick user
  delete '/projects/:id/:member_id' => 'projects#kick_user'

  # search
  get '/search' => 'projects#search', as: :search

  # project_like
  get '/projects/:id/like' => 'projects#like'
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :admin, class_name: "User"
    # has_and_belongs_to_many :members, class_name: "User", foreign_key: :user_id

    # likes
    has_many :project_likes
    has_many :liking_users, through: :project_likes, source: :user

    # tags
    has_and_belongs_to_many :tags, dependent: :destroy

    # request
    has_many :applications
    has_many :appliers, through: :applications, source: :user, dependent: :destroy

    # membership
    has_many :memberships
    has_many :members, through: :memberships, source: :user, dependent: :destroy

    has_attached_file :reference
    do_not_validate_attachment_file_type :reference

    scope :search_keyword, -> (keyword) { joins(:tags).where("content LIKE ? ", "%#{keyword}%") or where('title LIKE ? OR description LIKE ?', "%#{keyword}%", "%#{keyword}%")  }
    
    # project version control
    has_many :project_versions
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController 
    before_action :set_project, only: [:show, :edit, :update, :destroy, :apply, :cancel_apply, :accept, :decline, :kick_user, :like]
    before_action :authenticate_user!, except: [:show, :index, :search]

    def index
        @projects = Project.all
        @projects_bypage = @projects.order('created_at DESC').page params[:page]
    end  

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        @project.save

        input_tag = @project.tag_string
        input_tag = input_tag.gsub(", ", ",")
        tag_array = input_tag.split(',')
        tag_array.each do |tag|
            new_tag = Tag.create(project_id: @project.id, content: tag)
            @project.tags << new_tag
        end
       
        redirect_to @project
     end

    def search
        # parameters
        @keyword = params[:keyword]
        @maxMember = params[:maxMember].to_i
        @isKorean = params[:isKorean] == "true" if params[:isKorean].present?
        @isOnline = params[:isOnline] == "true" if params[:isOnline].present?
        @admin = params[:admin]
        @isClosed = params[:isClosed] == "1" if !params[:isClosed].nil?
        @tag = params[:tag]
        @skills = []
        @skills.push("%"+params[:skill1]+"%") if !params[:skill1].empty?
        @skills.push("%"+params[:skill2]+"%") if !params[:skill2].empty?
        @skills.push("%"+params[:skill3]+"%") if !params[:skill3].empty?
        @tools = []
        @tools.push("%"+params[:tool1]+"%") if !params[:tool1].empty?
        @tools.push("%"+params[:tool2]+"%") if !params[:tool2].empty?
        @tools.push("%"+params[:tool3]+"%") if !params[:tool3].empty?
        
        @results = Project.all
        keywordSearch = Project.all

        # main search: search for projects which include the keyword in [title, description, tags]
        # code @ models/project.rb
        keywordSearch = keywordSearch.search_keyword(@keyword).distinct if @keyword.present?

        # advanced search
        if @maxMember != 20
            @results = @results.where("maxMember <= ?", @maxMember)
        end
        @results = @results.where(isKorean: @isKorean) if !@isKorean.nil?
        @results = @results.where(isOnline: @isOnline) if !@isOnline.nil?
        @results = @results.joins(:admin).where("name like ?", "%#{@admin}%") if @admin.present?
        @results = @results.where((['skills LIKE ?'] * @skills.size).join(' OR '), *@skills) unless @skills.empty?
        @results = @results.where((['tools LIKE ?'] * @tools.size).join(' OR '), *@tools) unless @tools.empty?
        @results = @results.where(isClosed: @isClosed) if !@isClosed.nil?

        # user can decide whether to AND/OR keyword search results
        if params[:orAnd] == "OR"
            # if any of the advanced search fields is filled
            if (@maxMember != 20) | !@isKorean.nil? | !@isOnline.nil? | @admin.present? | !@skills.empty? | !@tools.empty? | !@isClosed.nil?
                # when the keyword search field is empty, search returns all projects by default.
                # exception in the case where any of the advanced search fields is filled; keyword search result is considered empty.
                if @keyword.present?
                    @results = @results | keywordSearch
                end
            else
                @results = keywordSearch
            end
        else
            @results = @results.search_keyword(@keyword).distinct if @keyword.present?
        end
    end

    def show
    end

    def edit
        check_user
    end

    def update
        @project.update(project_params)

        @project.tags.destroy_all
        input_tag = @project.tag_string
        input_tag = input_tag.gsub(", ", ",") # windows에서는 \r\n인데 mac에서는 \n이다.
        tag_array = input_tag.split(",") 
        tag_array.each do |tag|
            new_tag = Tag.create(project_id: @project.id, content: tag)
            @project.tags << Tag.find(new_tag.id)
        end

        redirect_to @project
    end

    def destroy
        project = Project.find(params[:id])
        project.destroy

        redirect_to root_url
    end

    def apply
        application_hash = {user_id: current_user.id, project_id: params[:id]}
        application = Application.where(application_hash)
        Application.create(application_hash)
    
        # redirect_to @project
        render json: {}
    end

    def cancel_apply
        application_hash = {user_id: current_user.id, project_id: params[:id]}
        application = Application.where(application_hash)
        application.destroy_all
        
        # redirect_to @project
        render json: {}
    end

    def user
        user_id = params[:id]
        @user = User.find(user_id)
        @projects = Project.page params[:page]
        @projects = @projects.where(admin_id: user_id)
        # @projects = Project.page params[:page]
    end

    def accept
        # add as member
        membership_hash = {user_id: params[:requester_id], project_id: params[:id]}
        membership = Membership.where(membership_hash)
        Membership.create(membership_hash)

        # remove from appliers
        application_hash = {user_id: params[:requester_id], project_id: params[:id]}
        application = Application.where(application_hash)
        application.destroy_all
    
        # redirect_to @project
        render json: {}
    end

    def decline
        application_hash = {user_id: params[:requester_id], project_id: params[:id]}
        application = Application.where(application_hash)
        application.destroy_all

        # redirect_to @project
        render json: {}
    end

    def kick_user
        membership_hash = {user_id: params[:member_id], project_id: params[:id]}
        membership = Membership.where(membership_hash)
        membership.destroy_all
        
        # redirect_to @project
        render json: {}
    end

    def like
        project_like_hash = {user_id: current_user.id, project_id: params[:id]}
        like = ProjectLike.where(project_like_hash)
        if like.empty?
            ProjectLike.create(project_like_hash)
        else
            like.destroy_all
        end

        # redirect_to @project
        render json: {}
    end

    private
        def set_project
            @project = Project.find(params[:id])
        end

        def project_params
            params.require(:project).permit(:admin_id, :title, :maxMember, :skills, :description, :isKorean, :isOnline, :tools, :reference, :isClosed, :tag_string)
        end

        def check_user
            if @project.admin != current_user
                redirect_to new_user_session_path
            end
        end
end 

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for project do |f| %>
    <div class="ui form">
        <%= f.hidden_field :admin_id, :value => current_user.id %>

        <div class="field">
            <%= f.label "프로젝트 제목 *" %>
            <%= f.text_field :title, :required => true %>
        </div>

        <div class="field">
            <%= f.label "프로젝트 설명 *" %>
            <%= f.text_area :description, size: "50x5", :required => true %>
        </div>

        <div class="field ui three column gird">
            <div class="ui three column grid">
                <div class="column">
                    <%= f.label "최대 인원" %>
                    <%= f.number_field :maxMember, min: 1 %>
                </div>
                <div class="column">
                    <%= f.label "사용 언어" %>
                    <%= f.select :isKorean, options_for_select([["한국어", true], ["English", false]], params[:isKorean]) %>
                </div>
                <div class="column">
                    <%= f.label "협업 방식" %>
                    <%= f.select :isOnline, options_for_select([["재택/온라인", true], ["오프라인 모임", false]], params[:isOnline]) %>
                </div>
            </div>
        </div>

        <div class="field">
            <%= f.label "필요한 스킬" %>
            <%= f.text_field :skills, placeholder: "ex) C 프로그래밍, 스와힐리어, ..." %>
        </div>

        <div class="field">
            <%= f.label "협업툴" %>
            <%= f.text_field :tools, placeholder: "ex) slack, github, trello, ..." %>
        </div>

        <div class="field">
            <%= f.label "첨부파일 (파일이 여러 개일 경우 zip파일로 모아서 첨부해주세요." %>
            <%= f.file_field :reference %>
        </div>

        <div class="field">
            <%= f.label "태그 (쉼표로 구분하여 입력해주세요)" %>
            <%= f.text_field :tag_string, placeholder: "ex) 심리학, 손 세정제, 어피치, ..." %>
        </div>

        <div class="field">
            <%= f.label "프로젝트 완료 여부" %>
            <%= f.check_box :isClosed, :value => params[:isClosed] %>
        </div>
        
        <%= f.submit "제출", :class => 'ui button' %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<br>
<h1>프로젝트 수정</h1>

<%= render 'form', project: @project %>

<br>
<p><%= link_to '메인 화면으로', projects_url %></p>
<br>

app/views/projects/index.html.erb
<br>

<h2>Featured Projects</h2>
<div class = "ui cards ui grid">
  <% @projects.sort_by{ |p| p.project_likes.where(created_at: Time.current.all_month).length }.reverse.each_with_index do |p, i| %>
    <div class="four wide column">
      <% if i < 4 %>
        <div class="ui card">
          <div class = "content">
            <div class = "header"><%= link_to p.title, p, class: "project-title" %></div>
            <div class = "meta"><%= link_to p.admin.name, "user/#{p.admin.id}", class: "project-admin" %></div>
            <% if p.isClosed == true %><a class="ui red label">완료</a>
            <% else %><a class="ui blue label">진행중</a>
            <% end %></br>
            <div class = "description"><%=p.description%></div>
          </div>
          <div class = "extra content">
            <% p.tags.each do |tag| %>
              <%= link_to tag.content, search_url(:keyword => tag.content, :maxMember => "20", 
              :skill1 => "", :skill2 => "", :skill3 => "", :tool1 => "", :tool2 => "", :tool3 => ""), class: "ui label", style: "margin-bottom: 5px;", method: :get %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

  <br>
  <h2>All Projects</h2>
  <div id="featured-projects-box">
    <% @projects_bypage.each_with_index do |p, i| %>
      <div class="ui segment">
        <%= link_to p.title, p, class: "project-title ui header" %><br>
        <%= link_to p.admin.name, "user/#{p.admin.id}", class: "project-admin" %><br>
        <% if p.isClosed == true %><a class="ui red label">완료</a>
        <% else %><a class="ui blue label">진행중</a>
        <% end %></br>
        <%= p.description %><br><br>
        <% p.tags.each do |tag| %>
          <%= link_to tag.content, search_url(:keyword => tag.content, :maxMember => "20", 
                :skill1 => "", :skill2 => "", :skill3 => "", :tool1 => "", :tool2 => "", :tool3 => ""), class: "ui label", style: "margin-bottom: 5px;",method: :get %>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>

  <div style = "display: flex; justify-content: center;">
    <%= paginate @projects_bypage%>
  </div>
  <br><br>

<script>
  $(document).ready(function() {
    $("#filter").on('click', function() {
      $("#filter-board").toggle();
    });
  });  
</script>

app/views/projects/new.html.erb
<br>
<h1>프로젝트 추가</h1>

<%= render 'form', project: @project %>

<br>
<p><%= link_to '메인 화면으로', projects_url %></p>
<br>

app/views/projects/search.html.erb
<br>
<h1>검색 결과</h1>
<% @results.reverse.each_with_index do |r, i| %>
  <div class="ui segment result" <% if i > 3 %> style="display: none;" <% end %>>
    <%= link_to highlight(r.title, @keyword), r, class: "project-title ui header" %><br>
    <%= link_to highlight(r.admin.name, @admin), "user/#{r.admin.id}", class: "project-admin" %><br>
    <%= highlight r.description, @keyword %><br><br>
    <% if @maxMember != 20 %>
      <div>최대 인원: <%= highlight r.maxMember.to_s, r.maxMember.to_s %>명</div>
    <% end %>
    <% if !@isOnline.nil? && (@isOnline == r.isOnline) %>
      <div>협업 방식:
        <% if @isOnline %>
            <%= highlight "재택/온라인", "재택/온라인" %>
        <% elsif !@isOnline %>
            <%= highlight "오프라인 모임", "오프라인 모임" %>
        <% end %>
      </div>
    <% end %>
    <% if !@isKorean.nil? && (@isKorean == r.isKorean) %>
      <div>사용 언어:
        <% if @isKorean %>
            <%= highlight "한국어", "한국어" %>
        <% elsif !@isKorean %>
            <%= highlight "English", "English" %>
        <% end %>
      </div>
    <% end %>
    <% if @skills != [] %>
      <div><%= highlight "필요한 스킬", "필요한 스킬" %>: <%= highlight r.skills, @skills %></div>
    <% end %>
    <% if @tools != [] %>
      <div><%= highlight "도구", "도구" %>: <%= highlight r.tools, @tools %></div>
    <% end %>
    <% if @isClosed && r.isClosed %>
      <div>마감 여부: <%= highlight "마감", "마감" %></div>
    <% end %>
    <% if r.isClosed == true %><a class="ui red label">완료</a>
    <% else %><a class="ui blue label">진행중</a>
    <% end %><br><br>
    <% r.tags.each do |tag| %>
      <%= link_to highlight(tag.content, @keyword), search_url(:keyword => tag.content, :maxMember => "20", 
        :skill1 => "", :skill2 => "", :skill3 => "", :tool1 => "", :tool2 => "", :tool3 => ""), class: "ui label", style: "margin-bottom: 5px;", method: :post %>
    <% end %>
  </div>
<% end %>
<% if @results.size > 4 %>
  <div class="fluid ui button" id="show-results">전체보기</div>
<% end %>

<script>
  $(document).ready(function() {
    $("#show-results").click(function() {
      $(".result").show();
      $(this).hide();
    })
  })
</script>

app/views/projects/show.html.erb
<br>
<!-- ui grid!-->
<div class="ui grid">
    <div class="twelve wide column">
        <div class="ui segment">
            <% if @project.isClosed == true %><a class="ui red ribbon label">완료</a>
            <% else %><a class="ui blue ribbon label">진행중 </a>
            <% end %>
            <!--제목!-->
            <h1 class="ui center aligned header">
                <% if @project.title.empty? || @project.title.nil? %>-
                <% else %><%= @project.title %>
                <% end %>
            </h1>
            <div style = "color: grey; text-align: center;">
                <a href='/user/<%= @project.admin.id %>'><%= @project.admin.name %></a>님이 생성하신 프로젝트입니다
            </div>
            <div style = "text-align: center;">
                <% if @project.description.empty? || @project.description.nil? %>-
                <% else %><%= @project.description%></p>
                <% end %>
            </div><br>
            <div style = "text-align: center;">
                <% if @project.tags.nil? %>-
                <% else %>
                    <% @project.tags.each do |tag|%>
                        <a class="ui label"><%= tag.content%></a>
                    <% end %>
                <% end %> 
            </div>
            <!--내용!-->   
            <table class="ui very basic table">
                <tbody>
                    <tr>
                    <td> 
                        <strong>최대 인원</strong> 
                        </td>
                        <td>
                            <% if @project.maxMember.nil? %>-
                            <% else %><%= @project.maxMember%>
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>언어</strong> 
                        </td>
                        <td>
                            <% if @project.isKorean == true %>한국어
                            <% else %>English
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>협업 방식</strong> 
                        </td>
                        <td>
                            <% if @project.isOnline == true %>재택/온라인
                            <% else %>오프라인 모임
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <td><strong>필요한 스킬</strong></td>
                        <td>
                            <% if @project.skills.nil? %>-
                            <% else %><%= @project.skills%>
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <td><strong>협업툴</strong></td>
                        <td>
                            <% if @project.tools.nil? %>-
                            <% else %><%= @project.tools%>
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <td><strong>첨부파일</strong></td>
                        <td>
                            <% if @project.reference_file_name.nil? %>-
                            <% else %>
                                <%= link_to @project.reference_file_name, @project.reference.url(:original), download: @project.reference.original_filename %></p>
                            <% end %>
                        </td>
                    </tr>
                </tbody>
            </table>        
        </div>
    </div>
    <!--내용 오른쪽 segment!-->            
    <div class="four wide column">
        <div class = "ui segment">
            <div class="ui center aligned red statistic">
                <div class="value" id="like-count">
                    <%= @project.project_likes.distinct.count(:id)%>
                </div>
                <div class="label">
                    likes
                </div>
            </div>
            <div>
            <strong>함께하는 멤버</strong>
                <% if @project.members.empty? %>
                    없음
                <% else %>
                    <table class = "ui very basic table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>E-mail</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @project.members.each do |member| %>
                                <tr>
                                    <td><a href='/user/<%= member.id %>'><%= member.name %></a></td>
                                    <td><a href='/user/<%= member.id %>'><%= member.email %></a></td>
                                    <% if member == current_user %><tr>(나)</tr><% end %>
                                    <% if @project.admin == current_user %>
                                        <td><a href='/projects/<%= @project.id%>/<%= member.id%>' data-method="DELETE"><button type="button">삭제</button></a></td>
                                    <% end %>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                <% end %>
            </div>
            <br>
            <div class = "ui buttons">
                <!-- 좋아요 버튼!-->
                <% if @project.liking_users.include? current_user%>
                    <a href = "/projects/<%=@project.id%>/like"><button class = "ui red basic button" id="ajax-like" data-project-id="<%=@project.id%>">좋아요 취소</button></a>
                <% else %>
                    <a href = "/projects/<%=@project.id%>/like"><button class = "ui blue basic button" id="ajax-like" data-project-id="<%=@project.id%>">좋아요</button></a>
                <% end %>
                <!--멤버신청 버튼!-->
                <% if current_user != @project.admin %>
                    <% if !user_signed_in? %>
                    <% elsif Membership.where(project_id: @project.id, user_id: current_user.id).empty? %>
                        <% if @project.appliers.include? current_user %>
                            <span id="ajax-apply"><a href="/projects/<%= @project.id%>/apply" data-method="DELETE"><button class = "ui red button"
                                                            data-project-id="<%=@project.id%>">멤버 신청 취소하기</button></a></span>
                        <% elsif @project.members.include? current_user %>
                        <% else %>
                            <span id="ajax-cancel-apply"><a href="/projects/<%= @project.id%>/apply"><button class = "ui blue button" 
                                                            data-project-id="<%=@project.id%>">멤버 신청하기</button></a></span>
                        <% end %>
                    <% end %>
                <%end%>
            </div>
        </div>
    </div>
    
    <div class="sixteen wide column">
        <!--현재유저가 어드민일 때!-->
        <% if current_user == @project.admin %>
            <div class="ui segment">
                <h1 class="ui center aligned header">멤버 신청자</h1>
                <div>
                    <% if @project.appliers.empty? %>없음
                    <% else %>
                        <table class = "ui very basic table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>E-mail</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @project.appliers.each do |applier| %>
                                    <tr>
                                        <td><a href='/user/<%= applier.id %>'><%= applier.name %></a></td>
                                        <td><a href='/user/<%= applier.id %>'><%=applier.email%></a></td>
                                        <td>
                                            <a href='/projects/<%= @project.id%>/accept/<%= applier.id%>'>승인</a>
                                            <a href='/projects/<%= @project.id%>/accept/<%= applier.id%>' data-method="DELETE">거절</a>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>



<script>
    $(document).ready(function() {
        $("#ajax-like").click(function(event) {
        event.preventDefault();
        event.stopPropagation();
        const project_id = $(this).data("project-id");
        
        $.ajax({
            type: "GET",
            dataType: "JSON",
            url: "/projects/"+project_id+"/like",
            data: {},
            success: function(data){
            $("#ajax-like").text() === "좋아요" ? $("#ajax-like").text("좋아요 취소") : $("#ajax-like").text('좋아요');
            $("#ajax-like").attr("class") == "ui red basic button" ? $("#ajax-like").attr("class", "ui blue basic button") : $("#ajax-like").attr("class", "ui red basic button");
            $("#ajax-like").text() === "좋아요" ? $("#like-count").text(Number($("#like-count").text())-1) : $("#like-count").text(Number($("#like-count").text())+1);
            }
        })
        })
    })
</script>

app/views/projects/user.html.erb
<br>
<h2 style = "text-align: center;"><%=@user.name%>님의 페이지입니다</h2>

<div class = "ui segment">
  <table class="ui very basic table">
    <tr>
      <td><strong>Name</strong></td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td><strong>E-mail</strong></td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td><strong>Institution</strong></td>
      <td><%= @user.institution %></td>
    </tr>
    <tr>
      <td><strong>Research Interest(s)</strong></td>
      <td><%= @user.research_interests %></td>
    </tr>
    <tr>
      <td><strong>Introduction</strong></td>
      <td><%= @user.introduction %></td>
    </tr>
  </table>
</div>

<br>
<h2 class = "text-align: center;">제안한 프로젝트</h2>

<div class = "ui cards ui grid">
    <% Project.where(admin_id: @user.id).each do |p| %>
        <div class="four wide column">
            <div class="ui card">
                <div class = "content">
                    <div class = "header"><%= link_to p.title, p, class: "project-title" %></div>
                    <div class = "meta"><%= link_to p.admin.name, "#{p.admin.id}", class: "project-admin" %></div>
                    <% if p.isClosed == true %><a class="ui red label">완료</a>
                    <% else %><a class="ui blue label">진행중</a>
                    <% end %></br>
                <div class = "description"><%=p.description%></div>
                </div>
                <div class = "extra content">
                    <% p.tags.each do |tag| %>
                    <%= link_to tag.content, search_url(:keyword => tag.content, :maxMember => "20", 
                    :skill1 => "", :skill2 => "", :skill3 => "", :tool1 => "", :tool2 => "", :tool3 => ""), class: "ui label", style: "margin-bottom: 5px;", method: :post %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
</div>


<br>
<h2 class = "text-align: center;">참여중인 프로젝트</h2>

<div class = "ui cards ui grid">
    <% Membership.where(user_id: @user.id).each do |m| %>
        <div class="four wide column">
            <div class="ui card">
                <div class = "content">
                    <div class = "header"><%= link_to Project.find(m.project_id).title, Project.find(m.project_id), class: "project-title" %></div>
                    <div class = "meta"><%= link_to Project.find(m.project_id).admin.name, "#{Project.find(m.project_id).admin.id}", class: "project-admin" %></div>
                    <% if Project.find(m.project_id).isClosed == true %><a class="ui red label">완료</a>
                    <% else %><a class="ui blue label">진행중</a>
                    <% end %></br>
                    <div class = "description"><%=Project.find(m.project_id).description%></div>
                </div>
                <div class = "extra content">
                    <% Project.find(m.project_id).tags.each do |tag| %>
                    <%= link_to tag.content, search_url(:keyword => tag.content, :maxMember => "20", 
                    :skill1 => "", :skill2 => "", :skill3 => "", :tool1 => "", :tool2 => "", :tool3 => ""), class: "ui label", style: "margin-bottom: 5px;", method: :post %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
</div>

