config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # signin/signup customizing
  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signup' => 'devise/registrations#new'
  end

  resources :projects
  root 'projects#index'

  # request
  get '/projects/:id/apply' => 'projects#apply'
  delete '/projects/:id/apply' => 'projects#cancel_apply'

  # mypage
  get '/mypage' => 'user#mypage'
  get '/mypage/edit' => 'user#edit'
  post '/mypage/edit' => 'user#update'

  # my projects
  get '/myprojects' => 'user#myprojects'

  # user information
  get '/user/:id' => 'projects#user'

  # accept
  get '/projects/:id/accept/:requester_id' => 'projects#accept'
  delete '/projects/:id/accept/:requester_id' => 'projects#decline'

  # kick user
  delete '/projects/:id/:member_id' => 'projects#kick_user'

  # search
  get '/search' => 'projects#search', as: :search

  # project_like
  get '/projects/:id/like' => 'projects#like'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OP</title>
    <%= csrf_meta_tags %>

    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "pushable">
    <div class = "pusher">
      <div class = "ui inverted vertical masthead center aligned segment">
        <div class ="ui container">
          <div class="ui large secondary inverted pointing menu">
            <div class ="left item"><%= link_to "OP", root_url, class: "item"%></div>
            <div class="right item">
              <% if user_signed_in? %>
                <%= link_to "새 프로젝트 만들기", new_project_url, class: "item" %>
                <div class="item ui dropdown">
                  <i class="user icon ui white circular label"></i>
                  <div class="text"><%= current_user.name %></div>
                  <i class="dropdown icon"></i>
                  <div class="menu">
                    <a class="item" href="/mypage/edit">나의 정보 수정</a>
                    <a class="item" href="/myprojects">내 프로젝트</a>
                    <a class="item" href="/users/sign_out" data-method="DELETE">로그아웃</a>
                  </div>
                </div>
              <% else %>
              <%= link_to "Log in", signin_url, class: "item" %>
              <%= link_to "Sign up", new_user_registration_url, class: "item" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="ui text container">
          <h1 class="ui inverted header">Open Project</h1>
          <h2>Find Interesting Projects!</h2><br>
        </div>
        <div class="ui stackable main container", id="this_form">
          <%= form_tag(search_url, method: :get) %>
            <div class="ui input huge fluid action">
              <%= search_field_tag 'keyword' %>
              <button class="ui icon button huge">
                <i class="search icon"></i>
              </button>
              <span id="filter" class="ui icon button huge">
                <i class="filter icon"></i>
              </span>
            </div>
            <div class="ui segment filter" id="filter-board" style="display: none;">
              <!--프로젝트명이랑 책임자 이름은 그냥 입력해서 검색하게 함.
              # 들어가면 태그로 인식하게 하기?! 정규표현식 써야 하나 어떻게 하는지 찾아 보기-->
              <div class = "ui form">
                <table class="ui very basic table">
                  <tr class="filter-board-attribute">
                    <td><%= label_tag "검색 방식" %></td>
                      <td><%= select_tag :orAnd, options_for_select([["OR", "OR", {class: "item"}], ["AND", "AND", {class: "item"}]]), class: "ui dropdown" %></td>
                      <td><%= label_tag "책임자 이름" %></td>
                      <td><%= text_field_tag "admin", nil, class: "field" %></td>
                  </tr>
                  <tr class="filter-board-attribute">
                    <td><%= label_tag "최대 인원(1~20)" %></td>
                    <td><%= number_field_tag "maxMember", "20", min: 1, max: 20 %></td>
                    <td><%= label_tag "사용 언어" %></td>
                    <td>
                      <div class = "field">
                        <div class = "ui radio checkbox">
                          <input type="radio" name="isKorean" value="true">
                          <label>한국어</label>
                        </div>
                      </div>
                      <div class = "field">
                        <div class = "ui radio checkbox">
                          <input type="radio" name="isKorean" value="false">
                          <label>English</label>
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr class="filter-board-attribute">
                    <td><label>협업 방식</label></td>
                    <td>
                      <div class = "field">
                        <div class="ui radio checkbox">
                        <input type="radio" name="isOnline" value="true">
                        <label>재택/온라인</label>
                        </div>
                      </div>
                      <div class = "field">
                        <div class = "ui radio checkbox">
                          <input type="radio" name="isOnline" value="false">
                          <label>오프라인 모임</label>
                        </div>
                      </div>
                    </td>
                    <td><label>모집 마감 여부</label></td>
                    <td>
                      <div class = "ui checkbox">
                        <%= check_box_tag "isClosed" %>
                        <label>마감</label>
                      </div>
                    </td>
                  </tr>
                  <tr class="filter-board-attribute">
                    <td><label>스킬 (최대 3개 입력 가능)</label></td>
                    <td>
                      <%= text_field_tag "skill1" %>
                      <%= text_field_tag "skill2" %>
                      <%= text_field_tag "skill3" %>
                    </td>
                    <td><label>도구 (최대 3개 입력 가능)</label></td>
                    <td>
                      <%= text_field_tag "tool1" %>
                      <%= text_field_tag "tool2" %>
                      <%= text_field_tag "tool3" %>
                    </td>
                  </tr>
                </table>
              </div>
            </div>
          </form>
        </div>
        <br>
      </div>
      <div class="ui main container">
        <%= yield %>
      </div>
    </div>
    <script>
      $(".ui.dropdown").dropdown();
    </script>
  </body>
</html>

<script>
  $(document).ready(function() {
    $("#filter").on('click', function() {
      $("#filter-board").toggle();
    });
  });  
</script>